### ISSUE TITLE
Labeling on your schematic

### ISSUE THREAD

**Issue by supercazzola** [F1SLP/Tracking-VFO-pour-YAESU-FT-817-et-FT-818-Arduino#1]
On the Schematic, for the connection to the radios, the numbering reflects sockets 1 for GND, 2 for TX and 3 for RX. But the actual pinouts for the connector would be 
1 for 13.8v
3 for GND
4 for TX
5 for RX

**Comment by F1SLP** [comment]
The schematic is corrected now.

Thanks for the remark.
